### ISSUE TITLE
用RequestVolley会内存泄露？

### ISSUE THREAD

**Issue by zyyoona7** [Jude95/RequestVolley#2]
···
 D/LeakCanary: In com.jude.joy:1.0:1.
                                                        \* com.jude.joy.module.main.MainActivity has leaked:
                                                        \* GC ROOT thread com.jude.volley.NetworkDispatcher.<Java Local> (named 'Thread-18376')
                                                        \* references com.jude.http.ByteArrayRequest.mListener
                                                        \* references com.jude.http.ByteArrayLoadController.mOnLoadListener
                                                        \* references com.jude.http.RequestManager$3.val$requestListener (anonymous class implements com.jude.http.LoadListener)
                                                        \* references com.jude.joy.module.text.TextJoyPresenter$1.this$0 (anonymous class extends com.jude.joy.model.callback.DataCallback)
                                                        \* references com.jude.joy.module.text.TextJoyPresenter.mAdapter
                                                        \* references com.jude.beam.expansion.list.BeamListFragmentPresenter$DataAdapter.mContext
                                                        \* leaks com.jude.joy.module.main.MainActivity instance
···

**Comment by Jude95** [comment]
是的，所以RequestManager.getInstance().init(this);请放在自定义Application里面。。
